/* Original Sentinel component. Streamlit v1 postMessage protocol, no external JS/CDNs. */
'use strict';
const root=document.getElementById('canvas');let map=null,current=null,reset=()=>{};
const send=(type,data={})=>window.parent.postMessage({isStreamlitMessage:true,type,...data},'*');
const select=(id,kind='entity')=>send('streamlit:setComponentValue',{value:{id,kind,nonce:Date.now()+Math.random()},dataType:'json'});
const colors={TELEFONO:'#3877a6',DISPOSITIVO:'#b58a25',SIM:'#c29757',PERSONA:'#188575',ANTENA:'#7a67a8',SERVICIO:'#95a3b2',VEHICULO:'#bc655c',PERFIL_DIGITAL:'#a160aa',EMPRESA:'#57937a'};
function el(tag,attrs={}){let n=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n}
function graph(args){
 root.replaceChildren();let svg=el('svg',{viewBox:'0 0 1000 650',role:'img','aria-label':'Grafo circular investigativo'});root.append(svg);let defs=el('defs'),arrow=el('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:5,markerHeight:5,orient:'auto-start-reverse'});arrow.append(el('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#7c96ab'}));defs.append(arrow);svg.append(defs);let group=el('g');svg.append(group);let nodes=args.nodes||[],edges=args.edges||[],positions=new Map();
 let targets=nodes.filter(n=>n.target),others=nodes.filter(n=>!n.target);
 function ring(ns,r){ns.forEach((n,i)=>{let a=2*Math.PI*i/Math.max(ns.length,1)-Math.PI/2;positions.set(n.id,{x:500+r*Math.cos(a),y:325+r*Math.sin(a)})})}ring(targets,targets.length===1?0:115);ring(others,260);
 let lines=[];edges.forEach(e=>{if(!positions.has(e.source)||!positions.has(e.destination))return;let line=el('line',{stroke:e.origin==='MANUAL'?'#538b7d':'#adbfce','stroke-width':Math.min(5,1+Math.log10(1+e.event_count)),'stroke-dasharray':e.effective_confidence==='CONFIRMADO'?'':'5 4',class:'edge','marker-end':'url(#arrow)',tabindex:0,role:'button','aria-label':e.kind});let title=el('title');title.textContent=e.kind+' · '+e.event_count+' eventos lógicos · '+e.effective_confidence;line.append(title);line.addEventListener('click',()=>select(e.id,'relation'));line.addEventListener('keydown',v=>{if(v.key==='Enter')select(e.id,'relation')});group.append(line);lines.push([line,e])});
 let elements=[];nodes.forEach(n=>{let g=el('g',{class:'node',tabindex:0,role:'button','aria-label':n.display_label});let r=n.target?24:17,c=colors[n.kind]||'#7189a0';let shape=el(n.kind==='DISPOSITIVO'?'rect':'circle',n.kind==='DISPOSITIVO'?{x:-15,y:-15,width:30,height:30,rx:4}:{r});shape.setAttribute('fill',n.target?'#164b76':c);shape.setAttribute('stroke',args.selected===n.id?'#edb642':'#fff');shape.setAttribute('stroke-width',args.selected===n.id?5:2);g.append(shape);let label=el('text',{'text-anchor':'middle',y:r+16,'font-size':n.target?13:11,fill:'#234760','font-weight':n.target?'bold':'normal'});label.textContent=n.display_label.length>28?n.display_label.slice(0,25)+'…':n.display_label;g.append(label);let title=el('title');title.textContent=n.kind+' · '+n.display_label;g.append(title);group.append(g);elements.push([g,n]);
 let moved=false,start=null;g.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};moved=false;g.setPointerCapture(e.pointerId)});g.addEventListener('pointermove',e=>{if(!start)return;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>3)moved=true;if(moved){let pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(group.getScreenCTM().inverse());positions.set(n.id,{x:pt.x,y:pt.y});draw()}});g.addEventListener('pointerup',()=>{if(!moved)select(n.id);start=null});g.addEventListener('keydown',e=>{if(e.key==='Enter')select(n.id)});
 });
 function draw(){for(let [g,n]of elements){let p=positions.get(n.id);g.setAttribute('transform',`translate(${p.x},${p.y})`)}for(let [l,e]of lines){let a=positions.get(e.source),b=positions.get(e.destination);let dx=b.x-a.x,dy=b.y-a.y,len=Math.max(1,Math.hypot(dx,dy)),margin=27;['x1','y1','x2','y2'].forEach((k,i)=>l.setAttribute(k,[a.x+dx/len*margin,a.y+dy/len*margin,b.x-dx/len*margin,b.y-dy/len*margin][i]))}}draw();let zoom=1;svg.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.4,Math.min(3,zoom*(e.deltaY>0?.9:1.1)));group.setAttribute('transform',`translate(${500*(1-zoom)},${325*(1-zoom)}) scale(${zoom})`)},{passive:false});reset=()=>{zoom=1;group.removeAttribute('transform')};
 document.getElementById('count').textContent=nodes.length+' entidades · '+edges.length+' relaciones';document.getElementById('legend').textContent='Azul: teléfono · Dorado: IMEI · Verde: persona · Línea discontinua: confianza no confirmada. Arrastra nodos; rueda para ampliar.';
}
function geography(args){
 root.replaceChildren();map=L.map(root,{zoomControl:true}).setView([25,-108],7);
 if(args.tiles)L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);
 let points=args.points||[],bounds=[];points.forEach(p=>{if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))return;bounds.push([p.lat,p.lon]);let marker=L.circleMarker([p.lat,p.lon],{radius:Math.min(20,7+Math.log2(1+(p.events||0))),fillColor:p.manual?'#16846b':p.objectives>1?'#ba8e2f':'#225f8e',fillOpacity:.85,color:args.selected===p.id?'#ecab22':'#fff',weight:2}).addTo(map);let card=document.createElement('div');let name=document.createElement('strong');name.textContent=p.address||p.label||p.site_key;card.append(name);let detail=document.createElement('p');detail.textContent=p.manual?'Ubicación documentada manualmente':`${p.events} eventos · ${p.objectives} objetivos · ${p.sectors} sectores`;card.append(detail);let warning=document.createElement('small');warning.textContent=p.manual?(p.source||'Captura manual'):'Sitio celular registrado; no posición GPS de una persona.';card.append(warning);marker.bindPopup(card);marker.on('click',()=>select(p.id));});
 reset=()=>{if(bounds.length)map.fitBounds(bounds,{padding:[35,35],maxZoom:14})};reset();document.getElementById('count').textContent=points.length+' ubicaciones agregadas';document.getElementById('legend').textContent=args.tiles?'Cartografía OSM activada · CDR y fichas permanecen en la aplicación.':'Modo sin cartografía externa · Activa OSM desde los filtros si lo necesitas.';
}
window.addEventListener('message',e=>{if(e.source!==window.parent||e.data.type!=='streamlit:render')return;let args=e.data.args;if(map){map.remove();map=null}current=args;if(args.mode==='map')geography(args);else graph(args);send('streamlit:setFrameHeight',{height:632})});
document.getElementById('reset').onclick=()=>reset();send('streamlit:componentReady',{apiVersion:1});send('streamlit:setFrameHeight',{height:632});
